### ISSUE TITLE
Automatically (or as standard) generate a new test dump

### ISSUE THREAD

**Issue by raar1** [PerfectFit-project/virtual-coach-issues#158]
For proper testing, we need the test dump to always be up to date with the current schema. At present this doesn't necessarily happen. Perhaps it would be useful to make a `populate_test_dump.py` utility script that builds a new test dump with some test users (and should be updated whenever the schema is).

At the very least we should add a test to github actions in https://github.com/PerfectFit-project/virtual-coach-db that checks if the schema in the test dump matches that in `models.py`. Failing that, it should block merging.

**Comment by svenvanderburg** [comment]
I am in favour of doing only the github action (I really like that suggestion). And leave how to fill the test dump to the developer.
