### ISSUE TITLE
Add Celery or http error handling for Celery task "trigger_rasa_reminder"

### ISSUE THREAD

**Issue by CunliangGeng** [PerfectFit-project/virtual-coach-issues#95]
This issue is created from PR #89 .

- [ ] Check the file `rasa_scheduler/rasa_scheduler/celery.py` and add Celery or http error handling for the Celery task `trigger_rasa_reminder`

See [No.4](https://denibertovic.com/posts/celery-best-practices/) to learn how to use Celery error handling

**Comment by wbaccinelli** [comment]
Substituted by #282
